CREATE TABLE Currency (
	CurrencyCode NVARCHAR(16) NOT NULL DEFAULT (''), 
	CurrencyName NVARCHAR(96) NOT NULL DEFAULT (''),
CONSTRAINT [IX_CurrencyCode] UNIQUE CLUSTERED 
	(
		CurrencyCode ASC
	)
) ON [PRIMARY]
GO

CREATE TABLE Bank (
	BankCode NVARCHAR(16) NOT NULL DEFAULT (''), 
	BankName NVARCHAR(96) NOT NULL DEFAULT (''),
CONSTRAINT [IX_BankCode] UNIQUE CLUSTERED 
	(
	BankCode ASC
	)
)ON [PRIMARY]
GO

CREATE TABLE CurDoc (
	DocNo NVARCHAR(10) NOT NULL DEFAULT(''),
	DocDate DATETIME NULL,
	DocGroup INT NOT NULL DEFAULT (0),
	BankCode NVARCHAR(16) NOT NULL DEFAULT (''), 
	Description NVARCHAR(256) NOT NULL DEFAULT ('')
CONSTRAINT [IX_DocNo] UNIQUE CLUSTERED 
	(
	DocNo ASC
	)
) ON [PRIMARY]
GO

CREATE TABLE CurDocDetail (
	DocNo NVARCHAR(10) NOT NULL DEFAULT (''), 
	CurrencyCode NVARCHAR(16) NOT NULL DEFAULT (''), 
	OriginalCurrency NUMERIC(15,3) NOT NULL DEFAULT (0),
	ExchangeRate NUMERIC(15,3) NULL DEFAULT ((0)), 
	VND NUMERIC(18,2) NULL DEFAULT ((0)))

CREATE TABLE CurOpen (
	CurrencyCode NVARCHAR(16) NOT NULL DEFAULT (''), 
	OriginalCurrency NUMERIC(15,3) NOT NULL DEFAULT (0), 
	VND NUMERIC(18,2) NULL DEFAULT ((0)),
CONSTRAINT [IX_CurrencyCode_Open] UNIQUE CLUSTERED 
	(
	CurrencyCode ASC
	)
) ON [PRIMARY]
GO
